### ISSUE TITLE
Possibly Javascript issue - timer does not increment

### ISSUE THREAD

**Issue by jrullo** [kromitgmbh/titra#10]
I'm seeing this in Chromium Inspection console:
Exception in setInterval callback: TypeError: this[b.p(...)] is not a function
    at f.p.get (99a0bdf436e896fb2f042dc053ab2e62cb419c14.js?meteor_js_resource=true:9)
    at e (/imports/ui/components/timetracker.js:1)
    at n.EnvironmentVariable.r.withValue (99a0bdf436e896fb2f042dc053ab2e62cb419c14.js?meteor_js_resource=true:1)
    at 99a0bdf436e896fb2f042dc053ab2e62cb419c14.js?meteor_js_resource=true:1
    at 99a0bdf436e896fb2f042dc053ab2e62cb419c14.js?meteor_js_resource=true:1

This error repeats every second. Clicking Start in app.titra.io/tracktime page always shows 00:00:00

I'm not sure what this is supposed to look like. The docs talk about entering times. I'm interested in time tracking live, not entering times recorded somewhere else. Not sure if I'm in the right place. I primarily use Toggl for time tracking. I'm hoping this can repalace toggl.

**Comment by faburem** [comment]
Thank you for reporting this issue, it is a regression we introduced when moving one of our dependencies from moment.js to dayjs. It is fixed in version [0.15.0](https://github.com/kromitgmbh/titra/releases/tag/0.15.0). The updated titra Docker image is currently being built and will be available soon.
