### ISSUE TITLE
OpenID Connect (OIDC) support

### ISSUE THREAD

**Issue by AndreasBomholtz** [kromitgmbh/titra#112]
I would like to add OpenID Connect (OIDC) support in Titra, but I just want to ask first what you guys thinks about it?

Because I can see that you are selling LDAP support, and I do not want to work against your business model.

Is this something you would be interested in?

**Comment by faburem** [comment]
Hi and thanks for reaching out!
We are very open for all kinds of pull requests and OIDC support is no exception. Before starting from scratch I think it is worth looking into existing implementations for the Meteor.js framework ([https://github.com/switch-ch/meteor-accounts-oidc](https://github.com/switch-ch/meteor-accounts-oidc)).
We are selling the LDAP support option because we believe businesses who need such an integration can afford the price tag and there is no working open source solution out there right now.
