### ISSUE TITLE
Not clear what archiving does

### ISSUE THREAD

**Issue by Julianoe** [kromitgmbh/titra#175]
Maybe it's a bit of a stupid question but I've been using Titra for a while, creating projects after projects. As I skimmed through those to do a bit of cleaning I wanted to archive them but I realize it's not clear to me what archiving a project does exactly.

I see that it's removed from the homepage but what else? The [wiki](https://wiki.titra.io/books/how-to-use-titra/page/time-tracking) only mentions "Select the Archive button to archive the project. (Project Owner only)" which is not really much better.

Sorry for the stupid question :)

**Comment by faburem** [comment]
First of all: there are no stupid questions 🤓
The idea behind archiving is that you usually don't want to delete a project right away - you probably know that situation, no work has been done for a customer in quite a while, you "close" the project but then there is a follow-up. That's the main reason why we opted for archiving as a first step instead of deleting projects directly. If you archive a project it will be hidden from all views with one exception:
After archiving a project you can display it still in the overview using the filter toggles:
<img width="1142" alt="image" src="https://github.com/kromitgmbh/titra/assets/11456790/d079183d-675c-4a85-800f-a0c4a1c0b779">

If you show archived projects you will see all archived projects in the overview and get additional buttons to restore and completely delete a project: 
<img width="1136" alt="image" src="https://github.com/kromitgmbh/titra/assets/11456790/0ae631b1-b9bb-4fb5-9415-79cdff65217f">

**Comment by faburem** [comment]
Added this to the official documentation at https://wiki.titra.io/books/how-to-use-titra/page/addedit-project#bkmrk-archiving-an-existin . I am therefore closing this issue. Feel free to create a new one if you have any other questions!

**Comment by Julianoe** [comment]
Awesome! I bet that'll make it clearer for forth coming users!
