### ISSUE TITLE
Feature request: Add different default rates on time trackes

### ISSUE THREAD

**Issue by John-H-Smith** [kromitgmbh/titra#199]
When tracking times, it would be nice if there was a field to modify the default rate for the tracked time.
As example: I add 50€ for a project as default rate. But for some communications like phone calls, I won't use the default rate as it is much to expensive. Therefor, as communication fee I would have for example 30€, but only for the specific tracked time.

**Comment by faburem** [comment]
we have recently added individual resource rates for projects, this is taking it one step further by adding rates per task which should be quite straight forward to add if you manage the tasks of projects on the project properties tab. I understand the use case for both, but have a hard time imagining a combination of the two 🤔
What do you think about adding a rate multiplier for tasks? You could use it to e.g. increase the default rate by 2 to double the rate for a complex task or reduce it by half by setting the multiplier to 0,5?

Thanks for your feedback!

**Comment by John-H-Smith** [comment]
Hi, in my opinion this would result in annoying try and error to get the rate I want to archive.
Maybe, you could add something like that: 
If a task is created for a project which has a rate set, the project's rate gets copied into the rate of the task. So, the user can overwrite it as needed.
For completeness, here's a mockup how it could look like: (to be approved by an ui/ux expert)

![2023-12-19_15-14](https://github.com/kromitgmbh/titra/assets/18233867/4a0f624a-254b-4de4-b887-2fbaa03896e1)

**Comment by faburem** [comment]
That's unfortunate, I really liked the weighting idea 😉 would have been easy to achieve.
Anyway - I can see where this is going and I think we can enable this as an opt-in feature. It needs a lot of adjusting in the backend logic though to make sure the correct rate is taken into account correctly everywhere.

**Comment by faburem** [comment]
this feature has finally shipped in titra version 0.97.0 🎉
The new feature is opt-in so you have to enable it under Administration > Global Settings:
<img width="1300" alt="image" src="https://github.com/kromitgmbh/titra/assets/11456790/cafedd80-0971-4a55-8bcf-1dd7c8350727">
As you can see in the screenshot we figured it might be helpful to show the calculated rate in the Details page, so you can now also opt-in to display the final rate there - because now it could be one of 1) task rate 2) resource rate or 3) project rate.
Once the setting is enabled, you can toggle individual task rates for any given task using the new icon displayed next to a task:
<img width="1316" alt="image" src="https://github.com/kromitgmbh/titra/assets/11456790/4f674075-7e8b-4173-bc1a-6fe04e39b671">

Sorry for the delay on this one, but we wanted to get it right!

**Comment by John-H-Smith** [comment]
Wow, looks great! I will notify if in production use are any problems!
Thank you very much!
