### ISSUE TITLE
Excel file is corrupted

### ISSUE THREAD

**Issue by AndreasBomholtz** [kromitgmbh/titra#210]
When downloading an Excel file, Excel can open it and use it.

But I can't copy anything or create new sheets in the document.

I get this error:
![image (2)](https://github.com/kromitgmbh/titra/assets/8829847/0f5ee74a-8ded-483b-9636-7c6914fb825e)

It used to work, but after I upgraded to version 0.97.2 from 0.95.6, the file was corrupted.

I'm using Microsoft Office 356 Business

**Comment by faburem** [comment]
Unfortunately I am not able to reproduce the issue. Can you maybe provide an example export so I can investigate further?
I even tried validating the generated files using Microft's OOXML Validator:
<img width="704" alt="image" src="https://github.com/kromitgmbh/titra/assets/11456790/240efe0c-1882-4f21-8c21-b5e844f06087">

**Comment by faburem** [comment]
I am really sorry but I still cannot reproduce the issue. I am also using Office 365 and can perfectly open and edit the example file without any problems. I tried creating a new sheet, copy content to the new sheet, moving multiple columns and everything else I could think of:
<img width="954" alt="image" src="https://github.com/kromitgmbh/titra/assets/11456790/044cbd52-83bb-4816-94aa-f79ca1710bea">
Also, the example file seems to be valid according to the validator:
<img width="711" alt="image" src="https://github.com/kromitgmbh/titra/assets/11456790/8a063510-e10f-4a18-9234-42a81240772e">
We are using the [nullxlsx library](https://github.com/Neovici/nullxlsx) to create the xlsx export without any titra specific modifications so I have no idea what could have changed since version 0.95.6.

**Comment by AndreasBomholtz** [comment]
Works on a other machine.
