### ISSUE TITLE
Unable to run docker container (Wekan integration)

### ISSUE THREAD

**Issue by tomonetml** [kromitgmbh/titra#31]
Hi,

I've installed Wekan with snap on Ubuntu server 14.04. i wanted to integrate your project into it but i cant' get it to work

sorry i'm not so good with docker. My port 3000 is already in use by another service.

I've tried

`docker run --name mongodb -p 27017:27017 mongo`

and then

`docker run --name titra -p 3010:3010 --link mongodb -e MONGO_URL=mongodb://mongodb/titra -e ROOT_URL=http://localhost:3010 kromit/titra`

but i get this error

`Unable to find image 'kromit/titra:latest' locally
latest: Pulling from kromit/titra
75cb2ebf3b3c: Pulling fs layer
1c6bd282486b: Pulling fs layer
f2fbfed8e1ed: Pulling fs layer
e2358783dc53: Waiting
e1a76eabfeb1: Waiting
b06119529ec6: Waiting
fa426a2fa159: Waiting
a1fb820ccf17: Waiting
fcc937781026: Waiting
docker: error pulling image configuration: unknown blob.`

i've also tried with composer

`curl -L https://github.com/faburem/titra/raw/master/docker-compose.yml | ROOT_URL=http://localhost:3010 docker-compose -f - up`

but i get 

`% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0/usr/local/bin/docker-compose: line 1: Not: command not found
100   131  100   131    0     0    837      0 --:--:-- --:--:-- --:--:--   839
100   142  100   142    0     0    427      0 --:--:-- --:--:-- --:--:--   427
100   353  100   353    0     0    663      0 --:--:-- --:--:-- --:--:--   663
(23) Failed writing body`

i'm using Docker version 18.06.3-ce, build d7080c1 and compose 1.27.0

what i'm doing wrong?
any help would be appreciated

ty
have a nice day
Matteo

**Comment by faburem** [comment]
Hi Matteo,
first please find the documentation for docker networking [here](https://docs.docker.com/config/containers/container-networking/). You can bind the default titra port (3000) to a custom port on your host. Based on your example you could do the following:
`docker run --name titra -p 3000:3010 --link mongodb -e MONGO_URL=mongodb://mongodb/titra -e ROOT_URL=http://localhost:3010 kromit/titra`
Second, I think there is a problem with the network on your docker host, based on your logs it looks to me like the Docker daemon fails to connect to the Docker container registry. Can you check if the internet access is working fine on the Docker host?

Best,
Fabian

**Comment by tomonetml** [comment]
Hi @faburem ty for your quick reply.
tomorrow morning i'll take a look into this.

i'm also trying to first make it work on docker on a synology nas, i can't download titra-latest it fails to download, but i can download 0.29.0 successfully

Matteo

**Comment by tomonetml** [comment]
Hi @faburem 

After some troubleshooting i moved to production site but get stuck at same point

![image](https://user-images.githubusercontent.com/34745293/92726702-4783e600-f36e-11ea-8155-eabe34c5591e.png)

![image](https://user-images.githubusercontent.com/34745293/92726725-55396b80-f36e-11ea-9b27-d58d7b78027d.png)

Hope i'm near solution, then need only to understand how to have it working at boot with a mounted volume for mongo datas

Matteo

**Comment by faburem** [comment]
Hi Matteo,
I think you are almost there, the culprit might be the ROOT_URL setting. Since you are using a dockerized environment I think you cannot use ROOT_URL=http://localhost:3000, can you try it with ROOT_URL=http:/10.0.1.100:3000.
Obviously also make sure the port number is matching the port number you expose to the host, so if you are binding to port 3010, the ROOT_URL should be set to http://10.0.1.100:300.
As other users reported previously it takes some time for the docker containers to boot up, so wait a minute or two before you try to access it through the browser.
Again, I think you almost got it working 👍
Please let me know if you are successful, I would appreciate a short tutorial how you set everything up so we can share it with the community 🕺

Best,
Fabian

**Comment by tomonetml** [comment]
![image](https://user-images.githubusercontent.com/34745293/92730498-2625f880-f374-11ea-8dae-4ba291f20d90.png)

Woohooo thank you! :yellow_heart:

now is time to have it working properly in production  :sweat_smile:

**Comment by tomonetml** [comment]
@faburem do you want the tutorial for Synolody DSM here in this discussion?

have a nice day
Matteo

**Comment by faburem** [comment]
I think we should close this issue and handle the tutorial separately. I would like to add it to the titra wiki. So it's up to you, if you are comfortable with the markdown syntax feel free to create a new issue and put the content there, otherwise you could also send us a document to team@kromit.at and we add it to the wiki.

Thanks for your efforts,
Fabian

**Comment by tomonetml** [comment]
ok i'll do
ty again
Matteo
