### ISSUE TITLE
Allow administrator and/or project-owner to edit/delete entries of other users

### ISSUE THREAD

**Issue by xadium** [kromitgmbh/titra#33]
If a member of staff makes a mistake in entry, the administrator/project owner cannot amend this.  It would be good for the edit/delete options to be shown for administrators/project owners.

**Comment by faburem** [comment]
Hi @xadium,
thanks for your feedback but this is actually by design. Since the main audience of titra is small teams we want to encourage communication inside the team. We are also using titra on a daily basis in production for our team of eight developers and if a change is needed it is done by the responsible team member.
However we are planning to offer an (paid) enterprise version of titra in the future which will include more sophisticated administrator features like this.

Best,
Fabian
