### ISSUE TITLE
Start time input makes it time impossible to edit a done task

### ISSUE THREAD

**Issue by Julianoe** [kromitgmbh/titra#58]
I saw in issue 35 https://github.com/kromitgmbh/titra/issues/35 that stop/start time should be implemented.

But every tracked item is shown to have started at 9am in the workingtime table.

Also if I set to true the "Track start time" in the admin, once I created a task and stopped tracking it and then try to switch it to another project by clicking on "edit", it tells me an error message "Please check your time input".

It seems that there is some kind of conflict or that the edit panel is waiting for a start time input (the start time input exists on the main form but not on the edit form.

edit: with further test I can in fact say that the Track button in /list/timecards/all does not work either because it does not contain the "Start time" input but expects it.

**Comment by faburem** [comment]
Thanks for reporting this issue!
There are actually two aspects I have fixed in version 0.48:
- time entries can now be edited when using the start time setting
- the working time details view is not compatible with the start time setting, thus it will not be displayed anymore when this setting is turned on. To provide some background information - this view is mostly used in Europe for regulatory requirements it is generated dynamically and does not respect the start time entries.

I hope this helps! Please let me know if we can close this issue or you have any further questions / concerns!

Thanks again,
Fabian

**Comment by faburem** [comment]
Can we close this issue?
