### ISSUE TITLE
Start/stop time : not shown on any other screen?

### ISSUE THREAD

**Issue by Julianoe** [kromitgmbh/titra#59]
That is more of a question but I wondered why the only screen you show the start/stop time is in "workingtime" and not in the other tabs like "daily" or "detailed"

**Comment by faburem** [comment]
Hi,
one of the main ideas behind titra is to keep it simple. That's why by default we don't display start / end time inputs. You can however enable it by setting the administration setting to true:
![image](https://user-images.githubusercontent.com/11456790/117545820-b877bc80-b027-11eb-960a-825bbaf3d462.png)

<img width="1379" alt="start time tracking" src="https://user-images.githubusercontent.com/11456790/117545959-5cf9fe80-b028-11eb-90b1-769da015eb98.png">

Once you enabled start time tracking you might be interested to display that information in the details pages
<img width="1366" alt="details with start time" src="https://user-images.githubusercontent.com/11456790/117545981-6d11de00-b028-11eb-88ab-324a1859d165.png">

To achieve this you can update the date format in the Administration > Settings to display the time information:
![image](https://user-images.githubusercontent.com/11456790/117546022-a0ed0380-b028-11eb-99c8-bf9482e3fef4.png)

**Comment by faburem** [comment]
Does this answer your question? If yes, can we close this issue?
